#!/bin/bash

# Update and ugrade the apt module
sudo apt-get update -y
sudo apt-get upgrade -y

# Install LAMP stack

# Apache
sudo apt-get install apache2 -y
# Mysql
sudo apt-get install mysql-server -y
# Install PHP and all its dependencies
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update
sudo apt-get install libapache2-mod-php php php-common php-xml php-mysql php-gd php-mbstring php-tokenizer php-json php-bcmath php-curl php-zip unzip -y

# Configure PHP (modifying the php.ini file)
PHP_INI_FILE="/etc/php/7.4/apache2/php.ini"

if [ -f "$PHP_INI_FILE" ]; then
    echo "Configuring PHP..."
    sudo sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' $PHP_INI_FILE
    echo "cgi.fix_pathinfo is set to 0."
else
    echo "PHP configuration file ($PHP_INI_FILE) not found. Manual configuration is required."
fi

# Restart apache to load changes
sudo systemctl restart apache2

# Install Composer
curl -sS https://getcomposer.org/installer | php

# Copy composer binary to a system directory
sudo cp composer.phar /usr/local/bin/composer
composer --version

COnfiguring Apache

cat >> /etc/apache2/sites-available/laravel.conf <<'EOF'
<VirtualHost *:80>
    ServerAdmin mfaiserl52@gmail.com
    ServerName Laravel
    DocumentRoot /var/www/html/laravel/public

    <Directory /var/www/html/laravel>
    Options Indexes MultiViews FollowSymLinks
    AllowOverride All
    Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF

sudo a2enmod rewrite
sudo a2ensite laravel.conf
sudo systemctl restart apache2

# Create Laravel project directory and clone repository
mkdir -p /var/www/html/laravel
cd /var/www/html/laravel
git clone https://github.com/laravel/laravel.git .

cd /var/www/html/laravel/
# Install Composer dependencies
sudo -u Altschool composer install --no-dev

# Set permissions
sudo chown -R www-data:www-data /var/www/html/laravel
sudo chmod -R 775 /var/www/html/laravel
sudo chmod -R 775 /var/www/html/laravel/storage
sudo chmod -R 775 /var/www/html/laravel/bootstrap/cache

# Copy the .env file (if it exists)
if [ -f .env.example ]; then
    cp .env.example .env
else
    echo "The .env.example file does not exist. You should create it manually."
fi

# Generate Laravel application key
php artisan key:generate

