#!/bin/bash

# Update and ugrade the apt module
sudo apt-get update -y
sudo apt-get upgrade -y

# Install LAMP stack

# Apache
sudo apt-get install apache2 -y
# Mysql
sudo apt-get install mysql-server -y
# Install PHP and all its dependencies
#sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update
sudo apt-get install libapache2-mod-php php php-common php-xml php-mysql php-gd php-mbstring php-tokenizer php-json php-bcmath php-curl php-zip unzip -y

# Configure PHP (modifying the php.ini file)
PHP_INI_FILE="/etc/php/7.4/apache2/php.ini"

if [ -f "$PHP_INI_FILE" ]; then
    echo "Configuring PHP..."
    sudo sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' $PHP_INI_FILE
    echo "cgi.fix_pathinfo is set to 0."
else
    echo "PHP configuration file ($PHP_INI_FILE) not found. Manual configuration is required."
fi

# Restart apache to load changes
sudo systemctl restart apache2

# Install Composer
curl -sS https://getcomposer.org/installer | php

# Copy composer binary to a system directory
sudo cp composer.phar /usr/local/bin/composer
composer --version
