#!/bin/bash


#Provision script for deploying LAMP stack

sudo apt-get update -y
sudo apt-get upgrade -y


#Install Apache web server

sudo apt-get install apache2 -y


#Install MySQL
sudo apt-get install mysql-server -y


#Install PHP and required extensions
sudo apt-get install php libapache2-mod-php php-mysql -y


#Restart Apache2 to apply changes
sudo systemctl restart apache2

# Clone a PHP application from Github
git clone https://github.com/laravel/laravel.git /var/www/html/myapp

# Configure Apache to serve the PHP application
sudo cp /var/www/html/myapp/config/app.php /etc/apache2/sites-available
sudo a2ensite myapp
sudo systemctl reload apache2

# Create the MySQL database and user for the application
mysql -u root -p -e "CREATE DATABASE myappdb;"
mysql -u root -p -e "CREATE USER 'Altschool'@'192.168.35.101' IDENTIFIED BY 'faisal12';"
mysql -u root -p -e "GRANT ALL PRIVILEGES ON myappdb.* TO 'Altschool'@'192.168.35.101'"
mysql -u root -p -e "FLUSH PRIVILEGES"
